# RBAC : Role-Based Access Control
# 권한정리를 도와주는 ClusterRole 

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-role

rules:
  - apiGroups: [""]
    resources: ["nodes", "nodes/metrics"]
    verbs: ["get", "list", "watch"] 


---
apiVersion: v1 
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: monitoring

--- 
# cluster role 과 service account 를 바인딩 
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-binding

# ClusterRole 참조
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-role

# ServiceAccount 참조
# apiGroup : core 그룹은 기본그룹으로 생략가능
subjects:
  - kind: ServiceAccount
    name: prometheus
    namespace: monitoring
