apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring

data: 
  # prometheus와 node-exporter 사이에서 수집된 정보를 몇 초 간격으로 전달 
  prometheus.yml: |
    global:
      scrape_interval: 15s 
    
    scrape_configs:
      - job_name: 'node-exporter' 
        kubernetes_sd_configs:
          - role: node
        relabel_configs:
          - source_labels: [__address__]
            regex: '(.*):10250'
            replacement: '${1}:9100'
            target_label: __address__


