apiVersion: cert-manager.io/v1
kind: ClusterIssuer 
metadata:
  name: order-issuer
  namespace: lgcns


spec:
  acme:
    # ca server address (인증서 발급진행) 
    server: https://acme-v02.api.letsencrypt.org/directory
    
    # 인증서 만료시 갱신할 정보 전달 메일주소 
    email: jslim9413@naver.com 

    privateKeySecretRef: 
      name:  order-issuer

    solvers:
    - http01:
        ingress:
          # cert-manager가 nginx 기반의 ingress controller 통신해서 검증 
          class: nginx 

---
apiVersion: cert-manager.io/v1
kind: Certificate 
metadata:
  name: server-inspireseop2283-shop-tls
  namespace: lgcns

spec:
  secretName: server-inspireseop2283-shop-tls
  issuerRef: 
    name: order-issuer
    kind: ClusterIssuer 
  commonName: server.inspireseop2283.shop
  dnsNames:
  # 서브도메인이 여러개일 경우 나열할 수 있다.
  - server.inspireseop2283.shop



